apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastream
  namespace: api
  labels:
    app: datastream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datastream
  template:
    metadata:
      labels:
        app: datastream
    spec:
      restartPolicy: Always
      containers:
        - name: datastream
          image: proto/datastream:0.1
          ports:
            - containerPort: 8080
          env:
            - name: INFRA
              value: kind/development
            - name: AWS_REGION
              value: us-west-2
            - name: WIKIMEDIA_API_USER_AGENT
              value: local/kafka-ingestion <you@email.com>
            - name: LOKI_ENDPOINT
              value: http://opentelemetry-collector.o11y:3500
            - name: OTLP_HTTP_ENDPOINT
              value: http://opentelemetry-collector.o11y:4318
            - name: OTLP_ZIPKIN_ENDPOINT
              value: http://opentelemetry-collector.o11y:9411
            - name: KAFKA_URL
              value: kafka.kafka.svc.cluster.local:9092
            - name: KAFKA_USERNAME
              value: datastream-user
            - name: KAFKA_PASSWORD
              value: datastream-password
            - name: KAFKA_TOPIC_PARTITIONS
              value: "3"
            - name: KAFKA_TOPIC_REPLICAS
              value: "2"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: datastream
  name: datastream
  namespace: api
spec:
  ports:
    - name: 'http'
      port: 8080
      targetPort: 8080
  selector:
    app: datastream
  type: ClusterIP
